import { Feather } from "@expo/vector-icons";
import React, { useState } from "react";
import { Alert, ScrollView, Text, TouchableOpacity, View, StyleSheet, TextInput } from "react-native";
import { useAuthContext } from "@/hooks/useAuth";
import { useCadastros } from "@/hooks/useCadastros";
import { useSolicitacaoMateriais } from "@/hooks/useSolicitacaoMateriais";
import { Cliente, Material } from "@/lib/osTypes";
import { SelectionModal } from "@/components/os/SelectionModal";
const C={bg:'#F5F7FB',card:'#fff',ink:'#152238',muted:'#687386',navy:'#0F2747',accent:'#1677FF',line:'#E4E9F0',danger:'#D64545'};
export default function MateriaisScreen(){const{auth}=useAuthContext();const cad=useCadastros();const f=useSolicitacaoMateriais();const[clienteModal,setClienteModal]=useState(false);const[materialModal,setMaterialModal]=useState(false);const tecnicoId=auth?.usuario?.colaborador_id;
 return <ScrollView contentContainerStyle={s.container}><View style={s.header}><View><Text style={s.kicker}>LOGÍSTICA</Text><Text style={s.title}>Solicitar material</Text><Text style={s.sub}>Faça o pedido antes do atendimento para agilizar o serviço.</Text></View><View style={s.icon}><Feather name="package" size={23} color="#fff"/></View></View>
 <View style={s.card}><Text style={s.section}>1. Selecione o cliente</Text><TouchableOpacity style={s.select} onPress={()=>setClienteModal(true)}><Feather name="briefcase" size={18} color={C.muted}/><Text style={s.selectText}>{f.cliente?f.cliente.nome:'Selecionar cliente'}</Text><Feather name="chevron-down" size={18} color={C.muted}/></TouchableOpacity>
 <Text style={s.section}>2. Adicione os materiais</Text><TouchableOpacity style={s.select} onPress={()=>setMaterialModal(true)}><Feather name="package" size={18} color={C.muted}/><Text style={s.selectText}>{f.material?`${f.material.nome} (${f.material.unidade})`:'Selecionar material'}</Text><Feather name="chevron-down" size={18} color={C.muted}/></TouchableOpacity>
 {f.material&&<><Text style={s.unit}>Quantidade em {f.material.unidade}</Text><View style={s.qtyRow}><TouchableOpacity style={s.qtyBtn} onPress={()=>f.setQuantidade(String(Math.max(.01,Number(f.quantidade)-1)))}><Text style={s.qtyBtnText}>−</Text></TouchableOpacity><TextInput style={s.qty} value={f.quantidade} onChangeText={f.setQuantidade} keyboardType="decimal-pad" textAlign="center"/><TouchableOpacity style={s.qtyBtn} onPress={()=>f.setQuantidade(String(Number(f.quantidade)+1))}><Text style={s.qtyBtnText}>+</Text></TouchableOpacity><TouchableOpacity style={s.add} onPress={f.adicionarItem}><Feather name="plus" size={16} color="#fff"/><Text style={s.addText}>Adicionar</Text></TouchableOpacity></View></>}
 {f.itens.length>0&&<View style={{marginTop:15}}><Text style={s.section}>Materiais solicitados</Text>{f.itens.map(x=><View key={x.material.id} style={s.item}><View style={{flex:1}}><Text style={s.itemName}>{x.material.nome}</Text><Text style={s.itemMeta}>{x.quantidade} {x.material.unidade}</Text></View><TouchableOpacity onPress={()=>f.removerItem(x.material.id)}><Feather name="trash-2" size={18} color={C.danger}/></TouchableOpacity></View>)}</View>}
 <TouchableOpacity style={[s.submit,(!f.cliente||!f.itens.length||f.enviando)&&{opacity:.45}]} disabled={f.enviando} onPress={()=>f.enviar(tecnicoId)}><Feather name="send" size={17} color="#fff"/><Text style={s.submitText}>{f.enviando?'ENVIANDO...':'ENVIAR SOLICITAÇÃO'}</Text></TouchableOpacity></View>
 <SelectionModal visible={clienteModal} title="Clientes" items={cad.clientes} emptyMessage="Nenhum cliente cadastrado." keyExtractor={(c:Cliente)=>c.id} renderLabel={(c:Cliente)=>`${c.nome}${c.bairro?` (${c.bairro})`:''}`} onSelect={(c:Cliente)=>{f.setCliente(c);setClienteModal(false)}} onClose={()=>setClienteModal(false)}/>
 <SelectionModal visible={materialModal} title="Materiais" items={cad.materiais} emptyMessage="Nenhum material cadastrado. Peça ao gestor para cadastrar no painel." keyExtractor={(m:Material)=>m.id} renderLabel={(m:Material)=><>{m.nome} <Text style={{color:C.muted}}>({m.unidade})</Text></>} onSelect={(m:Material)=>{f.setMaterial(m);setMaterialModal(false)}} onClose={()=>setMaterialModal(false)}/>
 </ScrollView>}
const s=StyleSheet.create({container:{padding:18,paddingBottom:35,backgroundColor:C.bg,flexGrow:1},header:{flexDirection:'row',justifyContent:'space-between',marginBottom:18},kicker:{fontSize:11,fontWeight:'800',letterSpacing:1,color:C.accent},title:{fontSize:25,fontWeight:'900',color:C.ink,marginTop:4},sub:{fontSize:13,color:C.muted,maxWidth:300,marginTop:5,lineHeight:18},icon:{width:48,height:48,borderRadius:15,backgroundColor:C.navy,alignItems:'center',justifyContent:'center'},card:{backgroundColor:C.card,borderRadius:22,padding:20,borderWidth:1,borderColor:C.line},section:{fontSize:15,fontWeight:'900',color:C.ink,marginBottom:10,marginTop:3},select:{minHeight:56,borderWidth:1,borderColor:C.line,borderRadius:15,paddingHorizontal:15,flexDirection:'row',alignItems:'center',gap:10,marginBottom:18,backgroundColor:'#FBFCFE'},selectText:{flex:1,fontSize:14,color:C.ink,fontWeight:'700'},unit:{fontSize:12,color:C.muted,fontWeight:'700',marginBottom:7},qtyRow:{flexDirection:'row',alignItems:'center',gap:7},qtyBtn:{width:42,height:48,borderRadius:13,backgroundColor:'#EEF2F7',alignItems:'center',justifyContent:'center'},qtyBtnText:{fontSize:24,fontWeight:'800',color:C.ink},qty:{width:70,height:48,borderRadius:13,borderWidth:1,borderColor:C.line,alignItems:'center',justifyContent:'center'},qtyText:{fontSize:16,fontWeight:'800',color:C.ink},add:{flex:1,height:48,borderRadius:13,backgroundColor:C.navy,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:6},addText:{color:'#fff',fontWeight:'800'},item:{flexDirection:'row',alignItems:'center',padding:13,borderRadius:13,borderWidth:1,borderColor:C.line,marginBottom:8},itemName:{fontSize:14,fontWeight:'800',color:C.ink},itemMeta:{fontSize:12,color:C.muted,marginTop:2},submit:{marginTop:18,height:54,borderRadius:15,backgroundColor:C.accent,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:8},submitText:{color:'#fff',fontWeight:'900',fontSize:14}});
